import { CONFIG } from '../config.js';
import { normalize, slugify } from '../utils/sanitize.js';
import { isConsultPrice } from '../utils/currency.js';
const state={products:[],byId:new Map(),bySlug:new Map(),categories:[],index:[],source:'local'};
export function setProducts(products,source='local'){state.products=products;state.source=source;state.byId=new Map(products.map((p)=>[p.id,p]));state.bySlug=new Map(products.map((p)=>[p.slug,p]));state.index=products.map((p)=>({p,name:normalize(p.name),code:normalize(p.codigo),cat:normalize(`${p.category} ${p.categoryRaw}`)}));const counts=new Map();products.forEach((p)=>counts.set(p.category,(counts.get(p.category)||0)+1));const order=CONFIG.categoryOrder;state.categories=[...counts.entries()].map(([name,count])=>({name,count,slug:slugify(name)})).sort((a,b)=>{const ia=order.indexOf(a.name),ib=order.indexOf(b.name);return(ia<0?99:ia)-(ib<0?99:ib)||a.name.localeCompare(b.name,'pt-BR');});}
export const getProducts=()=>state.products;export const getCategories=()=>state.categories;export const getById=(id)=>state.byId.get(String(id));export const getBySlug=(slug)=>state.bySlug.get(slug);export const getSource=()=>state.source;export const categoryBySlug=(slug)=>state.categories.find((c)=>c.slug===slug);
export function search(query,{limit=Infinity,category=''}={}){const q=normalize(query);let pool=state.index;if(category)pool=pool.filter((r)=>r.p.category===category);if(!q)return pool.slice(0,limit).map((r)=>r.p);const terms=q.split(' ').filter(Boolean),scored=[];for(const r of pool){let score=0,all=true;for(const t of terms){let s=0;if(r.code===t)s=100;else if(r.name.startsWith(t))s=40;else if(r.name.includes(` ${t}`))s=25;else if(r.name.includes(t))s=15;else if(r.code.startsWith(t))s=20;else if(r.cat.includes(t))s=6;if(!s){all=false;break;}score+=s;}if(all)scored.push([score,r.p]);}scored.sort((a,b)=>b[0]-a[0]||a[1].name.localeCompare(b[1].name,'pt-BR'));return scored.slice(0,limit).map((x)=>x[1]);}
export function sortProducts(list,mode){const arr=[...list],price=(p)=>(isConsultPrice(p.price)?Infinity:p.price);switch(mode){case'az':return arr.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));case'price-asc':return arr.sort((a,b)=>price(a)-price(b));case'price-desc':return arr.sort((a,b)=>{const pa=isConsultPrice(a.price)?-1:a.price,pb=isConsultPrice(b.price)?-1:b.price;return pb-pa;});default:return arr;}}
export function productsIn(category,limit=Infinity){return state.products.filter((p)=>p.category===category).slice(0,limit);}
