-- Content management for the verified owner account. No client receives a secret key.
alter table public.products add column if not exists image_path text;

create table if not exists public.site_banners (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  image_path text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.site_banners enable row level security;

create or replace function public.is_site_admin()
returns boolean language sql stable security invoker set search_path = '' as $$
  select (select auth.uid()) is not null
    and lower(coalesce((select auth.jwt())->>'email', '')) = 'juniorloiola777@gmail.com'
    and coalesce((select auth.jwt())->>'is_anonymous', 'false') = 'false';
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

revoke all on public.site_banners from public, anon;
grant select on public.site_banners to anon, authenticated;
grant insert, update, delete on public.site_banners to authenticated;
grant select, insert, update on public.products to authenticated;
grant usage, select on sequence public.site_banners_id_seq to authenticated;

create policy "Admin pode ler todos produtos" on public.products
  for select to authenticated using (public.is_site_admin());
create policy "Admin pode cadastrar produtos" on public.products
  for insert to authenticated with check (public.is_site_admin());
create policy "Admin pode editar produtos" on public.products
  for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

create policy "Banners ativos são públicos" on public.site_banners
  for select to anon, authenticated using (is_active);
create policy "Admin pode ler todos banners" on public.site_banners
  for select to authenticated using (public.is_site_admin());
create policy "Admin pode cadastrar banners" on public.site_banners
  for insert to authenticated with check (public.is_site_admin());
create policy "Admin pode editar banners" on public.site_banners
  for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
create policy "Admin pode apagar banners" on public.site_banners
  for delete to authenticated using (public.is_site_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-content', 'site-content', false, 10485760, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do nothing;

create policy "Leitura de imagens publicadas" on storage.objects
  for select to anon, authenticated using (
    bucket_id = 'site-content' and (
      exists (select 1 from public.products where is_active and image_path = name)
      or exists (select 1 from public.site_banners where is_active and image_path = name)
      or public.is_site_admin()
    )
  );
create policy "Admin envia imagens" on storage.objects
  for insert to authenticated with check (bucket_id = 'site-content' and public.is_site_admin());
create policy "Admin remove imagens" on storage.objects
  for delete to authenticated using (bucket_id = 'site-content' and public.is_site_admin());

insert into public.site_banners (id,title,description,sort_order,is_active)
values (1,'','',1,true),(2,'','',2,true),(3,'','',3,true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.site_banners','id'),(select max(id) from public.site_banners));
